#spring.application.name=journalapp
spring.data.mongodb.uri=mongodb+srv://sohailahmed989796_db_user:0YEq26M5kDkFRP9Z@cluster0.p0yup7n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.port=27017
spring.data.mongodb.database=journalapp
spring.data.mongodb.auto-index-creation=true


